import { describe, expect, it } from "vitest";

import {
  createContentPostListPreview,
  createDefaultEditorDoc,
  getContentPostFieldAvailabilityFromFieldSpecs,
} from "@/lib/content-runtime/shared";

describe("content runtime shared helpers", () => {
  it("builds normalized post-list previews with stable defaults", () => {
    expect(
      createContentPostListPreview({
        authorId: "author-1",
        createdAt: "2026-04-08T00:00:00.000Z",
        excerpt: "Short summary",
        id: "post-1",
        publishedAt: null,
        slug: "post-1",
        status: "draft",
        title: "Post 1",
        updatedAt: "2026-04-08T01:00:00.000Z",
      }),
    ).toEqual({
      authorId: "author-1",
      categoryIds: [],
      contentFields: {},
      contentFormat: "html",
      contentHtml: "",
      contentJson: createDefaultEditorDoc(),
      contentMarkdown: null,
      createdAt: "2026-04-08T00:00:00.000Z",
      customFields: {},
      editorPayloadReady: false,
      editingSession: null,
      excerpt: "Short summary",
      featuredImageUrl: null,
      focusKeyword: null,
      id: "post-1",
      parentPageId: null,
      publishedAt: null,
      redirects: [],
      seoDescription: null,
      seoTitle: null,
      slug: "post-1",
      status: "draft",
      tagIds: [],
      title: "Post 1",
      updatedAt: "2026-04-08T01:00:00.000Z",
    });
  });

  it("derives post field availability from semantic roles instead of storage field keys", () => {
    expect(
      getContentPostFieldAvailabilityFromFieldSpecs({
        customFields: [],
        fieldSpecs: [
          {
            allowedValues: null,
            contentFormat: null,
            editabilityState: "editable",
            fieldKey: "headline_text",
            label: "Headline",
            multiple: false,
            nullable: false,
            patchMode: "replace",
            readOnly: false,
            relationMode: "none",
            required: true,
            searchMode: "none",
            semanticRole: "title",
            uiControl: "text_input",
            valueKind: "text_like",
            visible: true,
          },
          {
            allowedValues: null,
            contentFormat: null,
            editabilityState: "editable",
            fieldKey: "workflow_state",
            label: "Workflow",
            multiple: false,
            nullable: true,
            patchMode: "replace",
            readOnly: false,
            relationMode: "none",
            required: false,
            searchMode: "none",
            semanticRole: "status",
            uiControl: "dropdown",
            valueKind: "enum",
            visible: true,
          },
          {
            allowedValues: null,
            contentFormat: null,
            editabilityState: "editable",
            fieldKey: "search_meta_title",
            label: "Search Title",
            multiple: false,
            nullable: true,
            patchMode: "replace",
            readOnly: false,
            relationMode: "none",
            required: false,
            searchMode: "none",
            semanticRole: "seoTitle",
            uiControl: "text_input",
            valueKind: "text_like",
            visible: true,
          },
          {
            allowedValues: null,
            contentFormat: null,
            editabilityState: "read_only",
            fieldKey: "keyword_phrase",
            label: "Keyword",
            multiple: false,
            nullable: true,
            patchMode: "no_write",
            readOnly: true,
            relationMode: "none",
            required: false,
            searchMode: "none",
            semanticRole: "focusKeyword",
            uiControl: "read_only",
            valueKind: "text_like",
            visible: true,
          },
        ],
      }),
    ).toMatchObject({
      focusKeyword: true,
      seo: true,
      seoTitle: true,
      status: true,
      title: true,
    });
  });
});
