export {
  createContentRuntimeAdapter,
  getRequiredContentRuntimeAdapterMethod,
} from "./postgres/factory";

export type {
  ContentAdapterArchiveExecutionRequest,
  ContentAdapterAuthorOptionsRequest,
  ContentAdapterAuthorsPageRequest,
  ContentAdapterCategoriesPageRequest,
  ContentAdapterCountPostsRequest,
  ContentAdapterCreateCollectionEntryRequest,
  ContentAdapterCreatePostExecutionRequest,
  ContentAdapterDeleteCollectionEntriesRequest,
  ContentAdapterDeletePostsRequest,
  ContentAdapterDiscardPostRequest,
  ContentAdapterLoadPostAuthorIdRequest,
  ContentAdapterLoadPostRequest,
  ContentAdapterMediaPageRequest,
  ContentAdapterPostEditorPayloadRequest,
  ContentAdapterPostListAuthorsRequest,
  ContentAdapterPostsPageRequest,
  ContentAdapterPostsPreviewSnapshot,
  ContentAdapterPostsPreviewSnapshotRequest,
  ContentAdapterPublishExecutionRequest,
  ContentAdapterRelationSearchRequest,
  ContentAdapterSavePostExecutionRequest,
  ContentAdapterTagsPageRequest,
  ContentAdapterUnpublishExecutionRequest,
  ContentAdapterUpdateCollectionEntryRequest,
  ContentAdapterWorkspaceCountsRequest,
  ContentAdapterWorkspaceSnapshotRequest,
  ContentProviderAdapter,
  ContentRuntimeAdapter,
  ContentSqlFamilyProviderAdapter,
} from "./postgres/factory";
